# drone_fleet/docker-compose.yml
version: '3.8'

services:
  honeydrone1:
    build: .
    container_name: honeydrone1
    networks:
      drone_net:
        ipv4_address: 172.20.0.10
    ports:
      - "2222:22"
      - "8080:80"
    environment:
      - ROLE=honeypot

  honeydrone2:
    build: .
    container_name: honeydrone2
    networks:
      drone_net:
        ipv4_address: 172.20.0.13
    ports:
      - "2223:22"
      - "8081:80"
    environment:
      - ROLE=honeypot

  realdrone1:
    build: .
    container_name: realdrone1
    networks:
      drone_net:
        ipv4_address: 172.20.0.11
    environment:
      - ROLE=mission

  realdrone2:
    build: .
    container_name: realdrone2
    networks:
      drone_net:
        ipv4_address: 172.20.0.12
    environment:
      - ROLE=mission

networks:
  drone_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
